[hekad]
cpuprof = "/var/log/hekad/cpuprof.log"
max_message_loops = 4
max_process_inject = 10
max_timer_inject  = 10
maxprocs = 10
memprof = "/var/log/hekad/memprof.log"
plugin_chansize = 10
poolsize = 100
hostname = "my.example.com"

[StatsdInput]
address = "127.0.0.1:8125"
ticker_interval = 1
stat_accum_name = "CustomStatAccum"

[CustomStatAccum]
type = "StatAccumInput"

[TcpInput]
address = "127.0.0.1:5565"
splitter = "HekaFramingSplitter"
decoder = "ProtobufDecoder"

[TcpInput2]
type = "TcpInput"
address = "127.0.0.1:5566"
splitter = "TokenSplitter"

[CounterFilter]
message_matcher = "Type != 'heka.counter-output'"
ticker_interval = 1

[PayloadEncoder]

[StatsdFileOutput]
message_matcher = "Type == 'heka.statmetric'"
type = "FileOutput"
path = "log/statsdonly.log"
encoder = "PayloadEncoder"

[CounterFileOutput]
type = "FileOutput"
path = "log/counter.log"
message_matcher = "Type == 'heka.counter-output'"

[LogOutput]
message_matcher = "Type == 'heka.counter-output'"
payload_only = true
