apiVersion: v1
kind: ReplicationController
metadata:
  name: monitoring-heapster-v8
  namespace: kube-system
  labels:
    k8s-app: heapster
    version: v8
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v8
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v8
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
        - image: gcr.io/google_containers/heapster:v0.17.0
          name: heapster
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
          command:
            - /heapster
            - --source=kubernetes:''
            - --sink=gcm
            - --sink=gcmautoscaling
            - --sink=gcl
            - --poll_duration=2m
            - --stats_resolution=1m
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs
              readOnly: true
      volumes:
        - name: ssl-certs
          hostPath:
            path: "/etc/ssl/certs"
