language: go
go:
    - 1.4
notifications:
    irc:
        channels:
            - "irc.mozilla.org#heka"
before_install:
    - sudo apt-get install protobuf-compiler cmake libgeoip-dev

install:
    - . build.sh

script:
    - make test
