language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - tip

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libpam-dev
  - go get github.com/msteinert/pam 

script: go build -v -tags "pam"

notifications:
  email:
    - u@gogs.io
  slack: gophercn:o5pSanyTeNhnfYc3QnG0X7Wx
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b590f8e03882f7aedc3e
    on_success: change 
    on_failure: always 
    on_start: never     
